Added statement that checks if drush is installed or not.

diff --git a/web_project_prepare b/web_project_prepare
--- a/web_project_prepare
+++ b/web_project_prepare
@@ -4,19 +4,27 @@
 # Web project prepare
 # By BratAnon / Anon
 #
+# Usage : ./web_project_prepare foo.dev
+#
 
 PROJECT_NAME=$1
 
-WEB_ROOT=/var/www
-PROJECT_WEB_ROOT=$WEB_ROOT/$PROJECT_NAME/web
-
-APACHE_VHOST_PATH=/etc/apache2/sites-available
-
-HOSTS=/etc/hosts
-IP_ADDRESS=127.0.0.1
-
 MYSQL_USER=root
 MYSQL_PASS=password
+
+WEB_ROOT=$HOME/www
+PROJECT_WEB_ROOT=$WEB_ROOT/$PROJECT_NAME/web
+
+APACHE_VHOST_PATH=/etc/httpd/conf/vhosts
+
+HOST_FILE=/etc/hosts
+IP_ADDRESS=127.0.0.1
+
+# Is drush installed?
+if ! hash drush 2>/dev/null; then
+  echo "I require drush but it's not installed.  Aborting.";
+  exit 1;
+fi
 
 if [ -z $PROJECT_NAME ]; then
   echo "I need a project name to continue."
@@ -65,7 +73,7 @@ echo "Restarting apache."
 sudo service apache2 restart
 
 #Add an instace to the HOSTS file
-sudo -- sh -c "echo '$IP_ADDRESS\t$PROJECT_NAME' >> $HOSTS "
+sudo -- sh -c "echo '$IP_ADDRESS\t$PROJECT_NAME' >> $HOST_FILE "
 echo "'$IP_ADDRESS $PROJECT_NAME' added to the host file."
 
 # Create mysql databas?
